openapi: 3.0.0
info:
  title: "CPU Info"
  description: "A simple server with open api 3"
  license:
    name: "Apache 2.0"
  version: "1.0"

servers:
  - url: http://localhost:8080/cloudmesh

paths:
  /cpu:
    get:
      summary: Returns cpu information of the server.
      operationId: cpu.get_processor_name
      responses:
        '200':
          description: CPU Information.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cpu"

components:
  schemas:
    cpu:
      type: "object"
      required:
        - "model"
      properties:
        model:
          type: "string"
